spring.application.name=projetoChaveiro
server.port=8090
spring.profiles.active=local

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# netstat -ano | findstr :8090
# taskkill /PID 20320 /F